name: Build MalumMenuXSicko
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Restore NuGet packages
      run: nuget restore MalumMenu.sln

    - name: Build Solution
      # We removed the /p:Platform part so it doesn't error out
      run: msbuild MalumMenu.sln /p:Configuration=Release
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: MalumMenu-DLL
        path: |
          **/Release/*.dll
          **/x64/Release/*.dll
          **/Win32/Release/*.dll